### ISSUE TITLE
Screen content won't scroll when it's wider than its container

### ISSUE THREAD

**Issue by javier-rosales** [javier-rosales/odin-calculator#1]
When calculator screen content (user input and result) needs more space than its container, it should enable a scroll because of the property:
```css
.screen__input {
    ....
    overflow-x: auto;
}

.screen__result {
    ...
    overflow-x: auto;
}
```
However, the content behaves like `overflow-x: hidden`, so it's not possible to see all the content.
